### ISSUE TITLE
Add info from LINUX_DEVICES.md

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/user#4]
The file LINUX_DEVICES.md in the OpenCPN root directory contains some important information for Linux users. However, this is a strange place for such info -- it would be better off in the User Manual.

The master branch contains some new support for handling these issues. However, the background in this document is still valid and important.

**Comment by rgleason** [comment]
It is there I believve

**Comment by rgleason** [comment]
Wait a minute  Linux.md  pleaee provide a link

**Comment by leamas** [comment]
https://github.com/OpenCPN/OpenCPN/blob/master/LINUX_DEVICES.md

**Comment by rgleason** [comment]
This is your recent work on Linux  devices?  USB, serial etc?  where bdbcat merged it?

You would like this duplicated under  Getting Started  > Linux
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:linux

Is that where?

**Comment by leamas** [comment]
For example there, google will find it anyway.

The merged PR: https://github.com/OpenCPN/OpenCPN/pull/2303

**Comment by rgleason** [comment]
Ok, yes this is the one I recall. https://github.com/OpenCPN/OpenCPN/pull/2303#issue-919657042

So the **content t**o use is
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:linux
and  https://github.com/OpenCPN/OpenCPN/pull/2303#issue-919657042

The **location** you want it is:
     
    Getting Started > Linux  > **Linux Devices** ?

**Comment by leamas** [comment]
There is no need to document the PR. Any need to document it is in fact a bug which should fixed.

What I want to be added to the manual is https://github.com/OpenCPN/OpenCPN/blob/master/LINUX_DEVICES.md, nothing else.  The exact location in the manual is not that important as long as there is  working link to it.

**Comment by rgleason** [comment]
Thanks, done

**Comment by leamas** [comment]
OK, I give up. If you  send user + pw to leamas dot alec at gmail, I'll try to fix the Linux section. It's a mess, and cannot be handled by minor edits.

**Comment by rgleason** [comment]
Alec , What is the problem?  Just saw this.  

You already have a PW but you probabbly lost it..   I have sent you another.

**Comment by leamas** [comment]
Yes, they are lost.  No new user/PW in my mailbox

**Comment by rgleason** [comment]
Will send the new Pw if you need it but you should have gotten an email too.

**Comment by leamas** [comment]
Fixed, closing
