### ISSUE TITLE
Flatpak: Misleading Flatpak FAQ  entry

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/user#9]
We have:

_Q: I am running Ubuntu linux. Tell me again why I should run, or even try, OpenCPN Flatpak? A: You probably would not want to run OpenCPN Flatpak, since OpenCPN is natively supported for Ubuntu. Downloads and updates are available for Ubuntu as normal from the OpenCPN PPA repository. But just to be clear: yes, you may run OpenCPN Flatpak on Ubuntu, if you would just like to try it out. It has some advantages_

This sort of misses the point. Correct answer: _A: One reason is when running a non-LTS Ubuntu release. The native .deb packages are only distributed for LTS releases, so Flatpak is the only officially supported packaging for other releases. Other reasons includes that the flatpak configuration is totally separated from the native packages' which makes it a good candidate for running for example  beta tests without risks for the regular setup._

**Comment by rgleason** [comment]
What is LTO? Is that Long Term ____?

**Comment by rgleason** [comment]
Is this in the wiki?

**Comment by rgleason** [comment]
FFound itt https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:background

**Comment by leamas** [comment]
Sorry, should be LTS (Long Time Support). Yes, it's in the wiki: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:background

**Comment by rgleason** [comment]
Fixed

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak:background

**Comment by leamas** [comment]
almost... _separated for the native_ should be _separated from the native_, my bad

**Comment by leamas** [comment]
done, closing
